default:
  create_shallow_trees:
    depth: -1

    min_depth: -1
    max_depth: -1
    allow_small_trees: false

  create_premise_masked_trees:
    premises_to_mask: 1

  search:
    max_steps: 100
    torch_devices: ['cuda:1']
    termination_criteria: []
    validator_names: ['GeneratedInput', 'ConsanguinityThreshold']

    nums_return_sequences: [10, 4]

    forward_agreement_validator_forward_model_name: 't5_large_pps_eb_step'
    forward_agreement_validator_entailment_model_name: 'wanli_entailment_model'
    forward_agreement_validator_agreement_threshold: 0.7
    forward_agreement_validator_mutual_entailment: true

    abductive_agreement_validator_abductive_model_name: 't5_abductive_step'
    abductive_agreement_validator_entailment_model_name: 'wanli_entailment_model'
    abductive_agreement_validator_agreement_threshold: 0.6
    abductive_agreement_validator_invalid_input_tolerance: 0
    abductive_agreement_validator_mutual_entailment: true

    consanguinity_threshold_validator_threshold: 1

  score_searches:
    score_method: ['rouge+entailment']
    score_type: ['missing_premises']
    eval_methods: ['max']
    score_steps: ['hypotheses']
    torch_devices: ['cuda:1']

  find_tree_proofs:
    proof_methods: ['RecoveredMissingPremise']
    threshold_values: [0.7]

  score_proofs:
    score_methods: ['forward_agreement']
    forward_step_model_name: 't5_large_pps_eb_step'
    torch_devices: ['cuda:1']

  convert_to_csv:
    write_step_types: ['intermediate', 'hypothesis']

  recover_premise_csv:
    write_step_types: [ 'intermediate', 'hypothesis' ]
    recover_threshold: 0.5

abductive_and_forward:
  search:
    heuristic: "StepTypeModeled"
    step_types: ["abductive", "forward"]
    step_model_names: ["t5_abductive_step", "t5_large_pps_eb_step"]

abductive_only:
  search:
    heuristic: "StepTypeModeled"
    step_types: [ "abductive" ]
    step_model_names: [ "t5_abductive_step" ]
    nums_return_sequences: [ 3 ]

  score_searches:
    score_method: ['rouge+entailment']
    score_type: ['missing_premises']
    eval_methods: [ 'max' ]
    score_steps: ['hypotheses']

  recover_premise_csv:
    write_step_types: [ 'hypothesis' ]

forward_only:
  search:
    heuristic: "StepTypeModeled"
    step_types: ["forward"]
    step_model_names: [ "t5_large_pps_eb_step" ]

  score_searches:
    score_method: ['rouge+entailment', 'entailment']
    score_type: ['missing_premises', 'goal']
    eval_methods: [ 'max', 'average' ]
    score_steps: ['intermediates']

  find_tree_proofs:
    proof_methods: [ 'IntermediateToGoal' ]
    threshold_values: [ 0.8 ]

  convert_to_csv:
    write_step_types: [ 'intermediate' ]

  recover_premise_csv:
    write_step_types: [ 'intermediate' ]

mac:
  search:
    torch_device: 'cpu'
